# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iwwoD48wizeYXMlWjkePtKkfZAqwEnLeGPTYftQ9lHjcPC1Rmizv0X0xBsJ0BpGqxt/CenADGpOHL0ioMEJYFdueQoe3aFcd5z8d/SAqPrNGbyDf4p7Qaw6pxhI/FQ/EN4OrcFhW8S4F6E4K/i7N/aK6w6bDzd8lXhuKj7nOE0HeUVvHJY8FzB42rpk4h5IFot4JBApnv/HZRoH+RqJ+bF+OFuKqO309OsCwevO/6Y7JMbKhZD/LgYsmShQBlcpgMecyW2OVd+iYIGm4loMJQUt8+d2qmq9p8HTmg1j/LTrCs685rDvh9pw88HUzZQ2oWipdnYXcyr2XZaWaAynW+RR2RAL/srUMSwxSaFXcTorSH56mbt+DxOjA74qEGeY/HH2W+7Wijjbt5Iyqo0+gs57xFzRmltbIB/TjAXv903IZqURs3oVXNYZEKBWwCXCGwZ1VWnbEQToiISfId1di70aNLobnyRHY53wk/oy7MV2sgBI6/S8907HFF3SvEBnBtH52GmuACrNp6YOft3Hz7IixvimZzifm6tysb7bpdjfckoFvc05FvY0/1VnVTp7NnVx7s3lerAvV4w6X9Lc1M3BpxuO3OY1yCIecAY6uk1xSvBHfgl9RVoTmMHENmzIyFH4n7XPfaciyCD6ey+qOxDYtXNJ+SCK7wy8l8qRBDgw="

matrix:
  include:
    - env: CONFIG=osx_python3.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi
