channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: bsddb3-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank
travis:
  secure:
    BINSTAR_TOKEN: iwwoD48wizeYXMlWjkePtKkfZAqwEnLeGPTYftQ9lHjcPC1Rmizv0X0xBsJ0BpGqxt/CenADGpOHL0ioMEJYFdueQoe3aFcd5z8d/SAqPrNGbyDf4p7Qaw6pxhI/FQ/EN4OrcFhW8S4F6E4K/i7N/aK6w6bDzd8lXhuKj7nOE0HeUVvHJY8FzB42rpk4h5IFot4JBApnv/HZRoH+RqJ+bF+OFuKqO309OsCwevO/6Y7JMbKhZD/LgYsmShQBlcpgMecyW2OVd+iYIGm4loMJQUt8+d2qmq9p8HTmg1j/LTrCs685rDvh9pw88HUzZQ2oWipdnYXcyr2XZaWaAynW+RR2RAL/srUMSwxSaFXcTorSH56mbt+DxOjA74qEGeY/HH2W+7Wijjbt5Iyqo0+gs57xFzRmltbIB/TjAXv903IZqURs3oVXNYZEKBWwCXCGwZ1VWnbEQToiISfId1di70aNLobnyRHY53wk/oy7MV2sgBI6/S8907HFF3SvEBnBtH52GmuACrNp6YOft3Hz7IixvimZzifm6tysb7bpdjfckoFvc05FvY0/1VnVTp7NnVx7s3lerAvV4w6X9Lc1M3BpxuO3OY1yCIecAY6uk1xSvBHfgl9RVoTmMHENmzIyFH4n7XPfaciyCD6ey+qOxDYtXNJ+SCK7wy8l8qRBDgw=
appveyor:
  secure:
    BINSTAR_TOKEN: hhS98dVbKVMiq1d7IEUyMCfA9Be1YSA2+BfDYf+1wwLYdOoWLWVaehGr6/mjqeAv
