channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: bsddb3-feedstock

provider:
  win: appveyor

azure:
  build_id: blank
appveyor:
  secure:
    BINSTAR_TOKEN: IKCEuGznkMky7EruV0O+eJIN6T8lOx/ALYBXKlouPz40BKPfqOky24LFZpTlS/5Y
